{
 "title": "Smard-Energy-Data (renewable)",
 "time": { "from": "now-7d", "to": "now-6m" },
 "panels": [
  {
   "title": "Renewable vs Conventional (current)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(smard_energydata{cat_name=\"Realisierte Erzeugung\",energy_type=\"renewable\"})",
     "legendFormat": "renewable"
    },
    {
     "expr": "smard_energydata{cat_name=\"Realisierte Erzeugung\",energy_type=\"neutral\"}",
     "legendFormat": "neutral"
    },
    {
     "expr": "sum(smard_energydata{cat_name=\"Realisierte Erzeugung\",energy_type=\"conventional\"})",
     "legendFormat": "conventional"
    }
   ]
  },
  {
   "title": "Renewable vs Conventional (1d avg)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg_over_time(smard_energydata{cat_name=\"Realisierte Erzeugung\",energy_type=\"renewable\"}[1d]))",
     "legendFormat": "renewable"
    },
    {
     "expr": "avg_over_time(smard_energydata{cat_name=\"Realisierte Erzeugung\",energy_type=\"neutral\"}[1d])",
     "legendFormat": "neutral"
    },
    {
     "expr": "sum(avg_over_time(smard_energydata{cat_name=\"Realisierte Erzeugung\",energy_type=\"conventional\"}[1d]))",
     "legendFormat": "conventional"
    }
   ]
  },
  {
   "title": "Renewable vs Conventional (7d avg)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg_over_time(smard_energydata{cat_name=\"Realisierte Erzeugung\",energy_type=\"renewable\"}[7d]))",
     "legendFormat": "renewable"
    },
    {
     "expr": "avg_over_time(smard_energydata{cat_name=\"Realisierte Erzeugung\",energy_type=\"neutral\"}[7d])",
     "legendFormat": "neutral"
    },
    {
     "expr": "sum(avg_over_time(smard_energydata{cat_name=\"Realisierte Erzeugung\",energy_type=\"conventional\"}[7d]))",
     "legendFormat": "conventional"
    }
   ]
  },
  {
   "title": "Renewable vs Conventional",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "smard_energydata{cat_name=\"Realisierte Erzeugung\",energy_type=\"neutral\"}",
     "legendFormat": "neutral"
    },
    {
     "expr": "sum(smard_energydata{cat_name=\"Realisierte Erzeugung\",energy_type=\"conventional\"})",
     "legendFormat": "conventional"
    },
    {
     "expr": "sum(smard_energydata{cat_name=\"Realisierte Erzeugung\",energy_type=\"renewable\"})",
     "legendFormat": "renewable"
    }
   ]
  },
  {
   "title": "Generated (DE)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "smard_energydata{cat_name=\"Realisierte Erzeugung\"}",
     "legendFormat": "{{module_name}}"
    }
   ]
  },
  {
   "title": "Consumed (DE)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "smard_energydata{cat_name=\"Realisierter Stromverbrauch\"}",
     "legendFormat": "{{module_name}}"
    }
   ]
  }
 ]
}